-- iGlow contact messages: public contact form storage + admin replies.
-- A executer dans Supabase (SQL Editor) apres le schema principal (supabase-schema.sql),
-- qui doit deja exister car il definit public.is_admin().

create table public.messages (
    id bigint generated by default as identity primary key,
    name text not null,
    phone text not null,
    email text not null,
    message text not null,
    admin_reply text,
    replied_at timestamptz,
    created_at timestamptz not null default now()
);

alter table public.messages enable row level security;

create policy "Anyone can send a message"
on public.messages for insert
with check (true);

create policy "Admins read all messages"
on public.messages for select
using (public.is_admin());

create policy "Admins reply to messages"
on public.messages for update
using (public.is_admin())
with check (public.is_admin());
