-- iGlow shop database: products, customers, orders, and order tracking.

create type public.user_role as enum ('customer', 'admin');
create type public.order_status as enum (
    'pending',
    'confirmed',
    'preparing',
    'shipped',
    'delivered',
    'cancelled'
);

create table public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    full_name text not null,
    phone text,
    role public.user_role not null default 'customer',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table public.products (
    id bigint generated by default as identity primary key,
    name text not null,
    description text not null default '',
    price_xof integer not null check (price_xof >= 0),
    stock integer not null default 0 check (stock >= 0),
    category text not null check (category in ('glitter-oil', 'lip-balm')),
    image_url text,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table public.orders (
    id bigint generated by default as identity primary key,
    customer_id uuid not null references public.profiles(id) on delete restrict,
    customer_name text not null,
    phone text not null,
    address text not null,
    total_xof integer not null default 0 check (total_xof >= 0),
    status public.order_status not null default 'pending',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table public.order_items (
    id bigint generated by default as identity primary key,
    order_id bigint not null references public.orders(id) on delete cascade,
    product_id bigint not null references public.products(id) on delete restrict,
    product_name text not null,
    unit_price_xof integer not null check (unit_price_xof >= 0),
    quantity integer not null check (quantity > 0),
    line_total_xof integer generated always as (unit_price_xof * quantity) stored
);

create table public.order_status_history (
    id bigint generated by default as identity primary key,
    order_id bigint not null references public.orders(id) on delete cascade,
    status public.order_status not null,
    note text,
    created_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.profiles
        where id = auth.uid() and role = 'admin'
    );
$$;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.profiles (id, full_name, phone)
    values (
        new.id,
        coalesce(new.raw_user_meta_data ->> 'full_name', ''),
        new.raw_user_meta_data ->> 'phone'
    );
    return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create trigger profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create trigger products_updated_at
before update on public.products
for each row execute function public.set_updated_at();

create trigger orders_updated_at
before update on public.orders
for each row execute function public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.order_status_history enable row level security;

create policy "Customers read their profile"
on public.profiles for select
using (id = auth.uid() or public.is_admin());

create policy "Customers update their profile"
on public.profiles for update
using (id = auth.uid())
with check (id = auth.uid());

create policy "Everyone reads active products"
on public.products for select
using (is_active = true or public.is_admin());

create policy "Admins manage products"
on public.products for all
using (public.is_admin())
with check (public.is_admin());

create policy "Customers create their orders"
on public.orders for insert
with check (customer_id = auth.uid());

create policy "Customers read their orders"
on public.orders for select
using (customer_id = auth.uid() or public.is_admin());

create policy "Admins update orders"
on public.orders for update
using (public.is_admin())
with check (public.is_admin());

create policy "Customers create their order items"
on public.order_items for insert
with check (
    exists (
        select 1 from public.orders
        where id = order_id and (customer_id = auth.uid() or public.is_admin())
    )
);

create policy "Customers read their order items"
on public.order_items for select
using (
    exists (
        select 1 from public.orders
        where id = order_id and (customer_id = auth.uid() or public.is_admin())
    )
);

create policy "Customers read their order history"
on public.order_status_history for select
using (
    exists (
        select 1 from public.orders
        where id = order_id and (customer_id = auth.uid() or public.is_admin())
    )
);

create policy "Admins manage order history"
on public.order_status_history for all
using (public.is_admin())
with check (public.is_admin());

insert into public.products (name, description, price_xof, stock, category, image_url)
values
    ('Rose Glow', 'Une huile pailletee qui illumine delicatement la peau.', 10000, 12, 'glitter-oil', 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=900&q=80'),
    ('Glow Oil', 'Une huile lumineuse pour une peau douce et eclatante.', 10000, 8, 'glitter-oil', 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=900&q=80'),
    ('Baume Rose', 'Un baume nourrissant pour des levres douces et sublimees.', 5000, 15, 'lip-balm', 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?auto=format&fit=crop&w=900&q=80'),
    ('Baume Transparent', 'Une formule simple pour hydrater et proteger les levres.', 5000, 10, 'lip-balm', 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80'),
    ('Duo iGlow', 'Deux baumes a levres pour varier vos envies beaute.', 8000, 6, 'lip-balm', 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=900&q=80');
